import { useState } from 'react'
import { ChevronDown } from 'lucide-react'

const faqs = [
  {
    q: 'Is it safe to delete these folders?',
    a: 'Yes - every folder Cypher Clean targets is auto-generated by your build toolchain. node_modules, .next, venv, target, .gradle and similar folders are all rebuilt by running npm install, pip install, mvn compile, etc. The safety scoring system flags anything modified recently so you never delete work in progress.',
  },
  {
    q: 'Does Cypher Clean send any data to the internet?',
    a: 'The core app - scanning, scoring, deleting - runs entirely on your machine with no network requests. The only cloud calls are: AI Project Analysis (Pro), which sends project metadata to GPT-4.1. No source code or file contents are ever transmitted.',
  },
  // {
  //   q: 'Why is there a scan limit on the free tier?',
  //   a: 'The 3-scan / 6-hour limit is how we make the Pro upgrade worthwhile without crippling the free experience. Most developers do one or two cleanup sessions at a time - the free limit comfortably covers that. Pro removes the limit entirely.',
  // },
  {
    q: 'How does Pro activation work?',
    a: 'Pro is purchased via Polar.sh - you\'ll receive a license key after checkout. Open Cypher Clean, go to Settings → Activate Pro, paste your key, and Pro activates immediately. No reinstall, no new download. The license is cached locally for 24 hours so Pro works even without internet; it re-validates silently in the background. If you cancel, the app reflects it within 60 seconds automatically.',
  },
  {
    q: 'What is AI Project Analysis?',
    a: 'It\'s a Pro feature that reads your project\'s README, package.json, pyproject.toml, pom.xml, and similar config files to detect your tech stack and generate a plain-English summary. It opens a modal showing project metadata, auto-detected technology tags, and three AI-generated cards: what the project does, how it works, and the main technologies used. Powered by GPT-4.1 - only project metadata is sent, no source code.',
  },
  {
    q: 'Which Windows versions are supported?',
    a: 'Windows 10 (64-bit, version 1903+) and Windows 11. The system tray, and Explorer right-click integration all rely on Windows shell APIs.',
  },
  // {
  //   q: 'Why does Windows show a warning when I run the installer?',
  //   a: 'Cypher Clean is an indie project and we haven\'t purchased a code-signing certificate yet (they cost a few hundred dollars per year). Without one, Windows SmartScreen flags the installer as "unrecognized" and shows a blue "Windows protected your PC" warning. Nothing is wrong with the file - it\'s the same warning Windows shows for any small developer\'s app on its first day. To proceed, click "More info" on the warning dialog, then click "Run anyway." We plan to sign future releases once revenue covers the cost. In the meantime, the source is reviewable on GitHub if you want to verify there\'s nothing harmful before running it.',
  // },
  {
    q: 'Can I undo a deletion?',
    a: 'Deletions go to a confirmation step before anything is removed. Once you confirm and the folders are deleted, they cannot be restored from inside Cypher Clean - you can regenerate them with your build tool. We recommend reviewing the safety scores carefully before confirming.',
  },
  {
    q: 'Is a Mac or Linux version planned?',
    a: 'Cypher Clean is currently Windows-only. Mac and Linux versions are on the roadmap. Stay tuned! ',
  },
]

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false)
  return (
    <div className={`glass border border-blue-500/10 rounded-xl overflow-hidden transition-all duration-200 ${open ? 'border-blue-500/25' : ''}`}>
      <button
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left group"
        onClick={() => setOpen(o => !o)}
      >
        <span className={`font-medium text-sm leading-snug transition-colors ${open ? 'text-white' : 'text-slate-300 group-hover:text-white'}`}>
          {q}
        </span>
        <ChevronDown
          size={16}
          className={`shrink-0 text-slate-500 transition-transform duration-200 ${open ? 'rotate-180 text-cyan-400' : ''}`}
        />
      </button>
      {open && (
        <div className="px-6 pb-5">
          <p className="text-slate-500 text-sm leading-relaxed border-t border-white/5 pt-4">{a}</p>
        </div>
      )}
    </div>
  )
}

export default function FAQ() {
  return (
    <section id="faq" className="py-24 relative">
      <div className="max-w-3xl mx-auto px-6">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-blue-500/20 bg-blue-500/5 text-blue-400 text-xs font-medium tracking-widest uppercase mb-4">
            FAQ
          </div>
          <h2 className="text-4xl font-black text-white tracking-tight mb-4">
            Common{' '}
            <span className="gradient-text">questions</span>
          </h2>
          <p className="text-slate-500 text-base">
            Everything you want to know before hitting Download.
          </p>
        </div>

        <div className="flex flex-col gap-3">
          {faqs.map((item, i) => (
            <FAQItem key={i} {...item} />
          ))}
        </div>
      </div>
    </section>
  )
}
